### ISSUE TITLE
regex for rizon.net #nibl ? 

### ISSUE THREAD

**Issue by omgbox** [DaVarga/slingxdcc#4]
hello friends, what is the correct regex for the Anime channel on rizon called #nibl

their release looks like this. i dont think we can use the !s directly through slingbox :octocat: 
>-<node> !s bleach
-ooinuza- Sending Results... To stop results /MSG ooinuza STOP - Full Listing at: http://nibl.co.uk/bots.php?search=bleach
-ooinuza- [2.9G] [Hatsuyuki-Tsuki]_Bleach_The_Movie_4_-_The_Hell_Verse_[1280x720][046AFCD8].mkv  /MSG Rhialto|IPv6 XDCC SEND 3
-ooinuza- [1.6G] [Hatsuyuki-Tsuki]_Bleach__The__Movie__4__-__The__Hell__Verse_[848x464][F6AC8B53].mkv  /MSG Rhialto|IPv6 XDCC SEND 4
-ooinuza- [350M] [Tsuki]_Bleach_-_315_[1280x720][233E13F4].mkv  /MSG Rhialto|IPv6 XDCC SEND 180
<Kona> http://i.iiko.moe/kona.txt - New file added - [2.1G] - [Anonymoose] Momotarou - Umi no Shinpei (DVD, 10bit) [0BA0429B].mkv - /MSG Kona XDCC SEND 282
-ooinuza- [350M] [Tsuki]_Bleach_-_316_[1280x720][6E1DEDA3].mkv  /MSG Rhialto|IPv6 XDCC SEND 181
-ooinuza- [350M] [Tsuki]_Bleach_-_317_[1280x720][EDEDBE82].mkv  /MSG Rhialto|IPv6 XDCC SEND 182
-ooinuza- [350M] [Tsuki]_Bleach_-_318_[1280x720][29911302].mkv  /MSG Rhialto|IPv6 XDCC SEND 183
-ooinuza- [350M] [Tsuki]_Bleach_-_319_[1280x720][308C0F03].mkv  /MSG Rhialto|IPv6 XDCC SEND 184
-ooinuza- [350M] [Tsuki]_Bleach_-_320_[1280x720][10550D44].mkv  /MSG Rhialto|IPv6 XDCC SEND 185
-ooinuza- [350M] [Tsuki]_Bleach_-_322_[1280x720][D916DD29].mkv  /MSG Rhialto|IPv6 XDCC SEND 186
-ooinuza- [450M] [Tsuki]_Bleach_-_323_[1280x720][46FDB47B].mkv  /MSG Rhialto|IPv6 XDCC SEND 187
-ooinuza- [460M] [Tsuki]_Bleach_-_324_[1280x720][44F7A3E8].mkv  /MSG Rhialto|IPv6 XDCC SEND 188
-ooinuza- [350M] [Tsuki]_Bleach_-_325_[1280x720][8C1B877B].mkv  /MSG Rhialto|IPv6 XDCC SEND 189
-ooinuza- [350M] [Tsuki]_Bleach_-_326_[1280x720][C252E31D].mkv  /MSG Rhialto|IPv6 XDCC SEND 190

**Comment by DaVarga** [comment]
Same problem as in #2. I am working on a complete rewrite that is going to take care of a lot of issues.
The server-side JavaScript is almost done. It just needs some testing and is much better maintainable and documented.

I hope it can bereleased soon.
